<a href="https://colab.research.google.com/github/eildes06/pandasss/blob/main/DAwPy_S4_class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Control-pandas'-display" data-toc-modified-id="Control-pandas'-display-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Control pandas' display</a></span></li><li><span><a href="#Constructors" data-toc-modified-id="Constructors-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Constructors</a></span><ul class="toc-item"><li><span><a href="#Do-elements-exist?" data-toc-modified-id="Do-elements-exist?-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Do elements exist?</a></span></li><li><span><a href="#Random-numbers" data-toc-modified-id="Random-numbers-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Random numbers</a></span></li><li><span><a href="#More-indexing-and-selection" data-toc-modified-id="More-indexing-and-selection-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>More indexing and selection</a></span></li></ul></li><li><span><a href="#Adding-rows-and-columns" data-toc-modified-id="Adding-rows-and-columns-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Adding rows and columns</a></span><ul class="toc-item"><li><span><a href="#Dropping-rows-and-columns" data-toc-modified-id="Dropping-rows-and-columns-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Dropping rows and columns</a></span></li></ul></li></ul></div>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

In [ ]:
# The "usual suspects"
import numpy as np
import pandas as pd

# Control pandas' display

In [ ]:
#https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html
pd.set_option('precision', 3)  #for floats  1.333333333333333333333   1.33
pd.options.display.max_rows = 5
pd.options.display.max_columns = 20
# also possible to set 'context'


# Constructors

In [ ]:
data = [i for i in range(10)]
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
pd.DataFrame(data, columns=['col1'])

col1
0      0
1      1
..   ...
8      8
9      9

[10 rows x 1 columns]

In [ ]:
df = pd.DataFrame(data, columns=['col1'])
df

col1
0      0
1      1
..   ...
8      8
9      9

[10 rows x 1 columns]

In [ ]:
df.columns

Index(['col1'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
df.values

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]], dtype=int64)

In [ ]:
s = set ([1, 2, 3, 3, 2, 1, 5, 3])
pd.DataFrame(s)

0
0  1
1  2
2  3
3  5

In [ ]:
m = np.arange(2, 15, 2)
m

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
df = pd.DataFrame(m)

In [ ]:
df.head()

0
0   2
1   4
2   6
3   8
4  10

In [ ]:
df.tail(2)

0
5  12
6  14

In [ ]:
df.sample(3)

0
1  4
0  2
3  8

In [ ]:
df.columns=['my_col_name']

In [ ]:
df

my_col_name
0             2
1             4
..          ...
5            12
6            14

[7 rows x 1 columns]

In [ ]:
df.shape

(7, 1)

In [ ]:
# random.randn   df.sample

In [ ]:
s1 = np.random.randint(2,10, size = 4)
s2 = np.random.randint(3,10, size = 4)
s3 = np.random.randint(4,15, size = 4)

In [ ]:
myDict= {'var1':s1,'var2':s2,'var3':s3}
df = pd.DataFrame(myDict)  #keys-> cols   #values - >values
df

var1  var2  var3
0     6     7    12
1     6     6    12
2     2     6    14
3     7     4    13

In [ ]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df.index = ['a', 'b', 'c', 'd']
df

var1  var2  var3
a     6     7    12
b     6     6    12
c     2     6    14
d     7     4    13

##  Do elements exist?

In [ ]:
'a' in {'a':1, 'b': 2}

True

In [ ]:
'var1' in df

True

In [ ]:
df.index.isin( [ 'a'  ]   )

array([ True, False, False, False])

In [ ]:
df.index.isin( [ 'a', 'b'  ]   )

array([ True,  True, False, False])

In [ ]:
filterx = df.index.isin( [ 'a', 'b'  ]   )

In [ ]:
df.index[filterx]

Index(['a', 'b'], dtype='object')

## Random numbers

In [ ]:
# random.seed() provides a clean start point
from numpy.random import randn

SEED = 100
np.random.seed(SEED)

In [ ]:
np.random.randn(3)

array([-1.74976547,  0.3426804 ,  1.1530358 ])

In [ ]:
np.random.randn(3)

array([-0.25243604,  0.98132079,  0.51421884])

In [ ]:
np.random.seed(SEED)
np.random.randn(3)

array([-1.74976547,  0.3426804 ,  1.1530358 ])

In [ ]:
import numpy as np
np.random.randn(3)


array([ 0.22117967, -1.07004333, -0.18949583])

## More indexing and selection

In [ ]:
#namespace  {names: objects}    {'print':  <function print>, 'dir': <function dir}

In [ ]:
import pandas   # --> pandas: <library pandas>
import pandas as pd  #  --> 'pd': <library pandas>

In [ ]:
df = df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df

In [ ]:
df['Y']

In [ ]:
df.Y  #SQL Syntax  'Y', 'Y_col' works  'Y col' does not

In [ ]:
df.columns[2]

In [ ]:
df [ df.columns[2]  ]
#type( df [ df.columns[2]  ])

In [ ]:
## extract a DataFrame

df [  ['Y']    ]

In [ ]:
df = pd.DataFrame(np.random.randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [ ]:
df

W      X      Y      Z
A -0.252  0.981  0.514  0.221
B -1.070 -0.189  0.255 -0.458
C  0.435 -0.584  0.817  0.673
D -0.104 -0.531  1.030 -0.438
E -1.118  1.619  1.542 -0.252

In [ ]:
df [  ['Y', 'W', 'Y']    ]   #  df ['Y' ]

Y      W      Y
A  0.514 -0.252  0.514
B  0.255 -1.070  0.255
C  0.817  0.435  0.817
D  1.030 -0.104  1.030
E  1.542 -1.118  1.542

In [ ]:
df [ "A":"C"  ]

W      X      Y      Z
A -0.252  0.981  0.514  0.221
B -1.070 -0.189  0.255 -0.458
C  0.435 -0.584  0.817  0.673

In [ ]:
df.loc[:  , 'Y':'Z']

Y      Z
A  0.514  0.221
B  0.255 -0.458
C  0.817  0.673
D  1.030 -0.438
E  1.542 -0.252

In [ ]:
# loc = locate based one index names   (A, B, C ... W X Y Z)
# iloc = (index locate) based the numpy indices  (0, 1, 2, 3 ... )

In [ ]:
df.loc[:  , 'Y': 'Z']

Y      Z
A  0.514  0.221
B  0.255 -0.458
C  0.817  0.673
D  1.030 -0.438
E  1.542 -0.252

In [ ]:
df.loc [  ['A', 'B'], ["Y", "Z"] ]

Y      Z
A  0.514  0.221
B  0.255 -0.458

In [ ]:
df.iloc[1:3 ,2:3 ]

Y
B  0.255
C  0.817

In [ ]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [ ]:
name_of_last = list(df.columns)[-1]

In [ ]:
df

W      X      Y      Z
A -0.252  0.981  0.514  0.221
B -1.070 -0.189  0.255 -0.458
C  0.435 -0.584  0.817  0.673
D -0.104 -0.531  1.030 -0.438
E -1.118  1.619  1.542 -0.252

# Adding rows and columns

In [ ]:
df['new'] = np.nan
df

W      X      Y      Z  new
A -0.252  0.981  0.514  0.221  NaN
B -1.070 -0.189  0.255 -0.458  NaN
C  0.435 -0.584  0.817  0.673  NaN
D -0.104 -0.531  1.030 -0.438  NaN
E -1.118  1.619  1.542 -0.252  NaN

In [ ]:
df['a'] = df['X'] + df['Y']
df

W      X      Y      Z  new      a
A -0.252  0.981  0.514  0.221  NaN  1.496
B -1.070 -0.189  0.255 -0.458  NaN  0.066
C  0.435 -0.584  0.817  0.673  NaN  0.233
D -0.104 -0.531  1.030 -0.438  NaN  0.498
E -1.118  1.619  1.542 -0.252  NaN  3.161

In [ ]:
df['E'] = 777
df

W      X      Y      Z  new      a    E
A -0.252  0.981  0.514  0.221  NaN  1.496  777
B -1.070 -0.189  0.255 -0.458  NaN  0.066  777
C  0.435 -0.584  0.817  0.673  NaN  0.233  777
D -0.104 -0.531  1.030 -0.438  NaN  0.498  777
E -1.118  1.619  1.542 -0.252  NaN  3.161  777

In [ ]:
df['W']

A   -0.252
B   -1.070
C    0.435
D   -0.104
E   -1.118
Name: W, dtype: float64

In [ ]:
df['T'] = [1, 2, 3, 4, 5]
df

W      X      Y      Z  new      a    E  T
A -0.252  0.981  0.514  0.221  NaN  1.496  777  1
B -1.070 -0.189  0.255 -0.458  NaN  0.066  777  2
C  0.435 -0.584  0.817  0.673  NaN  0.233  777  3
D -0.104 -0.531  1.030 -0.438  NaN  0.498  777  4
E -1.118  1.619  1.542 -0.252  NaN  3.161  777  5

In [ ]:
# Add a row (create a new object - append() is very expensive)

df.loc['F'] = [123 ]* len(df.columns)
df


W        X        Y        Z    new        a    E    T
A    -0.252    0.981    0.514    0.221    NaN    1.496  777    1
B    -1.070   -0.189    0.255   -0.458    NaN    0.066  777    2
..      ...      ...      ...      ...    ...      ...  ...  ...
E    -1.118    1.619    1.542   -0.252    NaN    3.161  777    5
F   123.000  123.000  123.000  123.000  123.0  123.000  123  123

[6 rows x 8 columns]

In [ ]:
fdnew = df.append (  { col: 666 for col in df.columns   }, ignore_index=True  )

In [ ]:
{ col: 666 for col in df.columns   }

{'W': 666,
 'X': 666,
 'Y': 666,
 'Z': 666,
 'new': 666,
 'a': 666,
 'E': 666,
 'T': 666}

In [ ]:
type({ col: 666 for col in df.columns   })

dict

In [ ]:
fdnew

W        X        Y        Z    new        a    E    T
0    -0.252    0.981    0.514    0.221    NaN    1.496  777    1
1    -1.070   -0.189    0.255   -0.458    NaN    0.066  777    2
..      ...      ...      ...      ...    ...      ...  ...  ...
5   123.000  123.000  123.000  123.000  123.0  123.000  123  123
6   666.000  666.000  666.000  666.000  666.0  666.000  666  666

[7 rows x 8 columns]

In [ ]:
fdnew.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
new_ix = list(df.index)

In [ ]:
new_ix

['A', 'B', 'C', 'D', 'E', 'F']

In [ ]:
new_ix.append('G')

In [ ]:
fdnew.index = new_ix
fdnew

W        X        Y        Z    new        a    E    T
A    -0.252    0.981    0.514    0.221    NaN    1.496  777    1
B    -1.070   -0.189    0.255   -0.458    NaN    0.066  777    2
..      ...      ...      ...      ...    ...      ...  ...  ...
F   123.000  123.000  123.000  123.000  123.0  123.000  123  123
G   666.000  666.000  666.000  666.000  666.0  666.000  666  666

[7 rows x 8 columns]

## Dropping rows and columns

In [ ]:
# axis=0  rows;   axis=1   cols
print(id(df))
ndf = df.drop('a', axis=1, inplace=False )
print(id(df), id(ndf))


1984263589600
1984263589600 1984265777312


In [ ]:
print(id(df))
ndf = df.drop('a', axis=1, inplace=True )
print(id(df), id(ndf))
print(ndf is None)

1984263589600
1984263589600 140735362935488
True


In [ ]:
df

W        X        Y        Z    E    T
A    -0.252    0.981    0.514    0.221  777    1
B    -1.070   -0.189    0.255   -0.458  777    2
..      ...      ...      ...      ...  ...  ...
E    -1.118    1.619    1.542   -0.252  777    5
F   123.000  123.000  123.000  123.000  123  123

[6 rows x 6 columns]

In [ ]:
df.drop( ['Z', 'E', 'T'], axis=1, inplace=True  )
df


W        X        Y
A    -0.252    0.981    0.514
B    -1.070   -0.189    0.255
..      ...      ...      ...
E    -1.118    1.619    1.542
F   123.000  123.000  123.000

[6 rows x 3 columns]

In [ ]:
df.drop( [ 'A', 'B', 'C', 'D'  ], axis=0, inplace=True)
df

W        X        Y
E   -1.118    1.619    1.542
F  123.000  123.000  123.000

In [ ]:
ser = pd.Series([1, 2, 4, 5, 234])
ser

0      1
1      2
2      4
3      5
4    234
dtype: int64

In [ ]:
ser[3]

5

In [ ]:
ser [ser>4]

3      5
4    234
dtype: int64

In [ ]:
df [df['X']>5]
df3 = df.copy()

In [ ]:
df3 [df3['Y']>0] [['W','Y']]

W        Y
E   -1.118    1.542
F  123.000  123.000